### ISSUE TITLE
Javascript Classes to be Completed

### ISSUE THREAD

**Issue by colegil2012** [colegil2012/Treehouse#3]
## TODO

_Courses left to complete the Treehouse Javascript Track_
- [ ] Javascript Loops, Arrays and Objects
- [ ] Jquery Basics
- [ ] Using Jquery Plugins
- [ ] Interactive Web Pages with Javascript
- [ ] AJAX Basics
- [ ] Understanding "this" in JavaScript
- [ ] Object-Oriented JavaScript
- [ ] The Module Pattern in JavaScript
- [ ] Node.js Basics
- [ ] Build a Simple Dynamic Site with Node.js
- [ ] npm Basics
- [ ] Using npm as a Task Runner
- [ ] Git Basics
- [ ] Express Basics
- [ ] Gulp Basics
- [ ] Angular Basics
- [ ] Mongo Basics
- [ ] Building a MEAN Application
- [ ] JavaScript Unit Testing
